<a href="https://colab.research.google.com/github/RojaCM/MACHINE-LEARNING-ROJA/blob/main/KFold%20cross%20validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
K - Fold cross validation

In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

In [5]:
digits=load_digits()

In [11]:
digits

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.],
        [ 0.,  0.,  0., ..., 16.,  9.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  2., ..., 12.,  0.,  0.],
        [ 0.,  0., 10., ..., 12.,  1.,  0.]]),
 'target': array([0, 1, 2, ..., 8, 9, 8]),
 'frame': None,
 'feature_names': ['pixel_0_0',
  'pixel_0_1',
  'pixel_0_2',
  'pixel_0_3',
  'pixel_0_4',
  'pixel_0_5',
  'pixel_0_6',
  'pixel_0_7',
  'pixel_1_0',
  'pixel_1_1',
  'pixel_1_2',
  'pixel_1_3',
  'pixel_1_4',
  'pixel_1_5',
  'pixel_1_6',
  'pixel_1_7',
  'pixel_2_0',
  'pixel_2_1',
  'pixel_2_2',
  'pixel_2_3',
  'pixel_2_4',
  'pixel_2_5',
  'pixel_2_6',
  'pixel_2_7',
  'pixel_3_0',
  'pixel_3_1',
  'pixel_3_2',
  'pixel_3_3',
  'pixel_3_4',
  'pixel_3_5',
  'pixel_3_6',
  'pixel_3_7',
  'pixel_4_0',
  'pixel_4_1',
  'pixel_4_2',
  'pixel_4_3',
  'pixel_4_4',
  'pixel_4_5',
  'pixel_4_6',
  'pixel_4_7',
  'pixel_5_0',
  'pixel_5_1',
 

In [12]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [13]:
from sklearn.model_selection import train_test_split

In [15]:
x_train,x_test,y_train,y_test=train_test_split(digits.data,digits.target,train_size=0.3)

In [16]:
lr=LogisticRegression()

In [17]:
lr.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
ypred=lr.predict(x_test)

In [19]:
lr.score(x_test,y_test)

0.958664546899841

In [20]:
svm=SVC()

In [21]:
svm.fit(x_train,y_train)
svm.score(x_test,y_test)

0.9745627980922098

In [22]:
from sklearn.model_selection import KFold

In [24]:
kf=KFold(n_splits=3)

In [25]:
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [26]:
[1,2,3,4,5,6,7,8,9]

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
for xtrain,xtest in kf.split([1,2,3,4,5,6,7,8,9]):
  print(xtrain,xtest)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


[1,2,3,4,5,6][7,8,9]
[4,5,6,7,8,9][1,2,3]
[1,2,3,4,5,6][7,8,9]

In [30]:
#defining a function

def get_score(model,xtrain,xtest,ytrain,ytest):
  model.fit(xtrain,ytrain)
  return model.score(xtest,ytest)

In [32]:
get_score(SVC(),x_train,x_test,y_train,y_test)

0.9745627980922098

In [33]:
from sklearn.model_selection import StratifiedKFold

In [34]:
fold=StratifiedKFold(n_splits=3)

In [42]:
score_lr=[]
score_svm=[]
score_random=[]
for xtrain_idx,xtest_idx in kf.split(digits.data):
  xtrain,xtest,ytrain,ytest=digits.data[xtrain_idx],digits.data[xtest_idx],digits.target[xtrain_idx],digits.target[xtest_idx]

  score_lr.append(get_score(SVC(),xtrain,xtest,ytrain,ytest))
  score_svm.append(get_score(LogisticRegression(),xtrain,xtest,ytrain,ytest))
  score_random.append(get_score(RandomForestClassifier(),xtrain,xtest,ytrain,ytest))

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _che

In [43]:
score_lr

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [44]:
score_svm

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]

In [45]:
score_random

[0.9415692821368948, 0.9515859766277128, 0.9282136894824707]

In [46]:
from sklearn.model_selection import cross_val_score

In [50]:
cross_val_score(SVC(),digits.data,digits.target,cv=2)

array([0.95439377, 0.95991091])